[build]
builder = "railpacks/python:3.13"

[deploy]
startCommand = "poetry run python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
PYTHON_VERSION = "3.13"
POETRY_VENV_IN_PROJECT = "true"
POETRY_CACHE_DIR = "/tmp/poetry_cache"

# The following must be set in Railway dashboard or secrets
# DATABASE_URL - PostgreSQL connection string
# SECRET_KEY - JWT secret key for authentication
# ALGORITHM - JWT algorithm (default: HS256)
# ACCESS_TOKEN_EXPIRE_MINUTES - Token expiration time (default: 30)
