
"""A generic template for alembic migrations."""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bdd28c363ef'
down_revision = '32a901478a6c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
