
"""A generic template for alembic migrations."""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bd70d447111'
down_revision = '7e0686f78c2e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll_options', sa.Column('votes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poll_options', 'votes')
    # ### end Alembic commands ###
