
"""A generic template for alembic migrations."""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0686f78c2e'
down_revision = '1bdd28c363ef'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('dislikes', sa.Integer(), nullable=True),
    sa.Column('poll_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_polls_id'), 'polls', ['id'], unique=False)
    op.create_table('poll_dislikes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'poll_id')
    )
    op.create_table('poll_likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'poll_id')
    )
    op.create_table('poll_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_options_id'), 'poll_options', ['id'], unique=False)
    op.create_table('poll_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['poll_options.id'], ),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'poll_id', name='uq_poll_vote_user_per_poll')
    )
    op.create_index(op.f('ix_poll_votes_id'), 'poll_votes', ['id'], unique=False)
    op.create_index(op.f('ix_poll_votes_option_id'), 'poll_votes', ['option_id'], unique=False)
    op.create_index(op.f('ix_poll_votes_poll_id'), 'poll_votes', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_votes_user_id'), 'poll_votes', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poll_votes_user_id'), table_name='poll_votes')
    op.drop_index(op.f('ix_poll_votes_poll_id'), table_name='poll_votes')
    op.drop_index(op.f('ix_poll_votes_option_id'), table_name='poll_votes')
    op.drop_index(op.f('ix_poll_votes_id'), table_name='poll_votes')
    op.drop_table('poll_votes')
    op.drop_index(op.f('ix_poll_options_id'), table_name='poll_options')
    op.drop_table('poll_options')
    op.drop_table('poll_likes')
    op.drop_table('poll_dislikes')
    op.drop_index(op.f('ix_polls_id'), table_name='polls')
    op.drop_table('polls')
    # ### end Alembic commands ###
