
"""A generic template for alembic migrations."""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982bab33a911'
down_revision = '4bd70d447111'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('poll_options', 'votes',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('poll_options', 'votes',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
